Remove stray reference to BF_NUMA_ENABLED
Since libnuma removed on this branch in favor of hwloc, this generated

NameError: name 'BF_NUMA_ENABLED' is not defined

when running python -m bifrost.version --config